// Generated by gencpp from file astar_nav/astar_controller.msg
// DO NOT EDIT!


#ifndef ASTAR_NAV_MESSAGE_ASTAR_CONTROLLER_H
#define ASTAR_NAV_MESSAGE_ASTAR_CONTROLLER_H

#include <ros/service_traits.h>


#include <astar_nav/astar_controllerRequest.h>
#include <astar_nav/astar_controllerResponse.h>


namespace astar_nav
{

struct astar_controller
{

typedef astar_controllerRequest Request;
typedef astar_controllerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct astar_controller
} // namespace astar_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::astar_nav::astar_controller > {
  static const char* value()
  {
    return "4b8dc54808bdbb73aea05acfc874e398";
  }

  static const char* value(const ::astar_nav::astar_controller&) { return value(); }
};

template<>
struct DataType< ::astar_nav::astar_controller > {
  static const char* value()
  {
    return "astar_nav/astar_controller";
  }

  static const char* value(const ::astar_nav::astar_controller&) { return value(); }
};


// service_traits::MD5Sum< ::astar_nav::astar_controllerRequest> should match
// service_traits::MD5Sum< ::astar_nav::astar_controller >
template<>
struct MD5Sum< ::astar_nav::astar_controllerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::astar_nav::astar_controller >::value();
  }
  static const char* value(const ::astar_nav::astar_controllerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::astar_nav::astar_controllerRequest> should match
// service_traits::DataType< ::astar_nav::astar_controller >
template<>
struct DataType< ::astar_nav::astar_controllerRequest>
{
  static const char* value()
  {
    return DataType< ::astar_nav::astar_controller >::value();
  }
  static const char* value(const ::astar_nav::astar_controllerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::astar_nav::astar_controllerResponse> should match
// service_traits::MD5Sum< ::astar_nav::astar_controller >
template<>
struct MD5Sum< ::astar_nav::astar_controllerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::astar_nav::astar_controller >::value();
  }
  static const char* value(const ::astar_nav::astar_controllerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::astar_nav::astar_controllerResponse> should match
// service_traits::DataType< ::astar_nav::astar_controller >
template<>
struct DataType< ::astar_nav::astar_controllerResponse>
{
  static const char* value()
  {
    return DataType< ::astar_nav::astar_controller >::value();
  }
  static const char* value(const ::astar_nav::astar_controllerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASTAR_NAV_MESSAGE_ASTAR_CONTROLLER_H
