// Generated by gencpp from file astar_nav/astar_controllerRequest.msg
// DO NOT EDIT!


#ifndef ASTAR_NAV_MESSAGE_ASTAR_CONTROLLERREQUEST_H
#define ASTAR_NAV_MESSAGE_ASTAR_CONTROLLERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Pose2D.h>

namespace astar_nav
{
template <class ContainerAllocator>
struct astar_controllerRequest_
{
  typedef astar_controllerRequest_<ContainerAllocator> Type;

  astar_controllerRequest_()
    : current_pose()
    , goal_pose()  {
    }
  astar_controllerRequest_(const ContainerAllocator& _alloc)
    : current_pose(_alloc)
    , goal_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _current_pose_type;
  _current_pose_type current_pose;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _goal_pose_type;
  _goal_pose_type goal_pose;





  typedef boost::shared_ptr< ::astar_nav::astar_controllerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::astar_nav::astar_controllerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct astar_controllerRequest_

typedef ::astar_nav::astar_controllerRequest_<std::allocator<void> > astar_controllerRequest;

typedef boost::shared_ptr< ::astar_nav::astar_controllerRequest > astar_controllerRequestPtr;
typedef boost::shared_ptr< ::astar_nav::astar_controllerRequest const> astar_controllerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::astar_nav::astar_controllerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::astar_nav::astar_controllerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::astar_nav::astar_controllerRequest_<ContainerAllocator1> & lhs, const ::astar_nav::astar_controllerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.current_pose == rhs.current_pose &&
    lhs.goal_pose == rhs.goal_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::astar_nav::astar_controllerRequest_<ContainerAllocator1> & lhs, const ::astar_nav::astar_controllerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace astar_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::astar_nav::astar_controllerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::astar_nav::astar_controllerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::astar_nav::astar_controllerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::astar_nav::astar_controllerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::astar_nav::astar_controllerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::astar_nav::astar_controllerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::astar_nav::astar_controllerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4aec306ac0dd88e9ce0459a13eb6a7ee";
  }

  static const char* value(const ::astar_nav::astar_controllerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4aec306ac0dd88e9ULL;
  static const uint64_t static_value2 = 0xce0459a13eb6a7eeULL;
};

template<class ContainerAllocator>
struct DataType< ::astar_nav::astar_controllerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "astar_nav/astar_controllerRequest";
  }

  static const char* value(const ::astar_nav::astar_controllerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::astar_nav::astar_controllerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D current_pose\n"
"geometry_msgs/Pose2D goal_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::astar_nav::astar_controllerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::astar_nav::astar_controllerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_pose);
      stream.next(m.goal_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct astar_controllerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::astar_nav::astar_controllerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::astar_nav::astar_controllerRequest_<ContainerAllocator>& v)
  {
    s << indent << "current_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.current_pose);
    s << indent << "goal_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASTAR_NAV_MESSAGE_ASTAR_CONTROLLERREQUEST_H
